<?php defined('BASEPATH') OR exit('No direct script access allowed');?>
<div style="display: flex;
            flex-direction: column;
            align-items: center;
            padding: 10px;
            background-color: #FAF9FB;">
<h1 style="color:black;">Privacy Policy</h1>
<hr class="join-hr">

</div>
<div style="padding: 10px;background-color:#FAF9FB;">
<p style='margin-top:6.0pt;margin-right:0in;margin-bottom:6.0pt;margin-left:0in;font-size:11.0pt;font-family:"Calibri","sans-serif";'><span style='font-family:"Bookman Old Style","serif";'>Effective date: 25 May 24</span></p>
<p style='margin-top:6.0pt;margin-right:0in;margin-bottom:6.0pt;margin-left:0in;font-size:11.0pt;font-family:"Calibri","sans-serif";'><span style='font-family:"Bookman Old Style","serif";'>Last updated on: 25 May 24</span></p>
<p style='margin-top:6.0pt;margin-right:0in;margin-bottom:6.0pt;margin-left:0in;font-size:11.0pt;font-family:"Calibri","sans-serif";'><strong><span style='font-family:"Bookman Old Style","serif";'>1. GENERAL</span></strong></p>
<p style='margin-top:6.0pt;margin-right:0in;margin-bottom:6.0pt;margin-left:21.3pt;font-size:11.0pt;font-family:"Calibri","sans-serif";'><span style='font-family:"Bookman Old Style","serif";'>a.&nbsp;This Website and mobile application with the URL of bloodlinks.in (&quot;Website/Site&quot;) is operated by <strong><span style="color:red;">Vita HEE Care Trust</span></strong>(&apos;We/Our/Us&quot;). We are committed to protecting and respecting your privacy. We collect your personal and health information and process your personal data in accordance with the IT Act, 2000 (21 of 2000) and other national and state laws that relate to the processing of personal data. Please read the following carefully to understand our views and practices regarding your personal data.</span></p>
<p style='margin-top:6.0pt;margin-right:0in;margin-bottom:6.0pt;margin-left:21.3pt;font-size:11.0pt;font-family:"Calibri","sans-serif";'><span style='font-family:"Bookman Old Style","serif";'>b. &nbsp; This policy applies where we are acting as a data controller with respect to the personal data of bloodlinks.in and its service users; in other words, where we determine the purposes and means of the processing of that personal data.</span></p>
<p style='margin-top:6.0pt;margin-right:0in;margin-bottom:6.0pt;margin-left:21.3pt;font-size:11.0pt;font-family:"Calibri","sans-serif";'><span style='font-family:"Bookman Old Style","serif";'>c. &nbsp;We collect your personal information in order to provide and continually improve our products and services.</span></p>
<p style='margin-top:6.0pt;margin-right:0in;margin-bottom:6.0pt;margin-left:21.3pt;font-size:11.0pt;font-family:"Calibri","sans-serif";'><span style='font-family:"Bookman Old Style","serif";'>d. &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp;Our privacy policy is subject to change at any time without notice. To make sure you are aware of any changes, please review this policy periodically.</span></p>
<p style='margin-top:6.0pt;margin-right:0in;margin-bottom:6.0pt;margin-left:21.3pt;font-size:11.0pt;font-family:"Calibri","sans-serif";'><span style='font-family:"Bookman Old Style","serif";'>e. &nbsp;All partner firms and any third-party working with or for Us, and who have access to personal information, will be expected to read and comply with this policy.</span></p>
<p style='margin-top:6.0pt;margin-right:0in;margin-bottom:6.0pt;margin-left:0in;font-size:11.0pt;font-family:"Calibri","sans-serif";'><strong><span style='font-family:"Bookman Old Style","serif";'>2. HOW WE COLLECT THE INFORMATION</span></strong></p>
<p style='margin-top:6.0pt;margin-right:0in;margin-bottom:6.0pt;margin-left:21.3pt;font-size:11.0pt;font-family:"Calibri","sans-serif";'><span style='font-family:"Bookman Old Style","serif";'>a. &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp;From you directly and through this Site: We may collect information through the Website when you visit the site and fill out your details or provide such information to our representative. The data we collect depends on the context of your interactions with our website.</span></p>
<p style='margin-top:6.0pt;margin-right:0in;margin-bottom:6.0pt;margin-left:21.3pt;font-size:11.0pt;font-family:"Calibri","sans-serif";'><span style='font-family:"Bookman Old Style","serif";'>b. &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp;Through business interaction: We may collect information through business interaction with you or&nbsp;your&nbsp;representative.</span></p>
<p style='margin-top:6.0pt;margin-right:0in;margin-bottom:6.0pt;margin-left:21.3pt;font-size:11.0pt;font-family:"Calibri","sans-serif";'><span style='font-family:"Bookman Old Style","serif";'>c. &nbsp;From other sources: We may receive information from other sources, such as public databases; joint marketing partners; social media platforms; or other third parties such as:</span></p>
<p style='margin-top:6.0pt;margin-right:0in;margin-bottom:6.0pt;margin-left:.5in;font-size:11.0pt;font-family:"Calibri","sans-serif";'><span style='font-family:"Bookman Old Style","serif";'>I. &nbsp; &nbsp; &nbsp; &nbsp;Updated delivery and address information from our carriers or other third parties, which we use to correct our records and deliver our services or communication more easily.</span></p>
<p style='margin-top:6.0pt;margin-right:0in;margin-bottom:6.0pt;margin-left:.5in;font-size:11.0pt;font-family:"Calibri","sans-serif";'><span style='font-family:"Bookman Old Style","serif";'>II.&nbsp; &nbsp; &nbsp; &nbsp;Information about your interactions with the products and services offered by our subsidiaries.</span></p>
<p style='margin-top:6.0pt;margin-right:0in;margin-bottom:6.0pt;margin-left:0in;font-size:11.0pt;font-family:"Calibri","sans-serif";'><strong><span style='font-family:"Bookman Old Style","serif";'>3. INFORMATION WE COLLECT</span></strong></p>
<p style='margin-top:6.0pt;margin-right:0in;margin-bottom:6.0pt;margin-left:21.3pt;font-size:11.0pt;font-family:"Calibri","sans-serif";'><span style='font-family:"Bookman Old Style","serif";'>a. &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp;We collect information primarily to provide better services to all of our customers.</span></p>
<p style='margin-top:6.0pt;margin-right:0in;margin-bottom:6.0pt;margin-left:21.3pt;font-size:11.0pt;font-family:"Calibri","sans-serif";'><span style='font-family:"Bookman Old Style","serif";'>b. &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp;We collect the following information from you when you use or signup on our Website:&nbsp;</span></p>
<p style='margin-top:6.0pt;margin-right:0in;margin-bottom:6.0pt;margin-left:.5in;font-size:11.0pt;font-family:"Calibri","sans-serif";'><span style='font-family:"Bookman Old Style","serif";'>name, email, mobile number, UID, address, age, health record, blood group, last blood donation date, your geographical location, device ID, FCM token, device operating system, IP address (&quot;usage data&quot;). The usage data may include [your IP address, geographical location, browser type and version, operating system, referral source, length of visit, page views and website navigation paths, as well as information about the timing, frequency and pattern of your service use]. The source of the usage data is [our analytics tracking system]. This usage data may be processed [for the purposes of analysing the use of the website and services].</span></p>
<p style='margin-top:6.0pt;margin-right:0in;margin-bottom:6.0pt;margin-left:21.3pt;font-size:11.0pt;font-family:"Calibri","sans-serif";'><span style='font-family:"Bookman Old Style","serif";'>c. &nbsp;We do collect the following sensitive personal information from you when you use or sign up on our Website:</span></p>
<p style='margin-top:6.0pt;margin-right:0in;margin-bottom:6.0pt;margin-left:.5in;font-size:11.0pt;font-family:"Calibri","sans-serif";'><span style='font-family:"Bookman Old Style","serif";'>&nbsp;name, email, mobile number, UID, address, age, health record, medical history and blood group</span></p>
<p style='margin-top:6.0pt;margin-right:0in;margin-bottom:6.0pt;margin-left:21.3pt;font-size:11.0pt;font-family:"Calibri","sans-serif";'><span style='font-family:"Bookman Old Style","serif";'>d. &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp;When you visit our Site, some information is automatically collected. This may include information such as the Operating System (OS) running on your device, Internet Protocol (IP) address, access times, browser type, and language, and the website you visited before our Site. We also collect information about how you use Our products or services.</span></p>
<p style='margin-top:6.0pt;margin-right:0in;margin-bottom:6.0pt;margin-left:21.3pt;font-size:11.0pt;font-family:"Calibri","sans-serif";'><span style='font-family:"Bookman Old Style","serif";'>e. &nbsp;We automatically collect your content use history, which we sometimes aggregate with similar information from other customers to create features such as maximum demand,&nbsp;most rare,&nbsp;etc.</span></p>
<p style='margin-top:6.0pt;margin-right:0in;margin-bottom:6.0pt;margin-left:21.3pt;font-size:11.0pt;font-family:"Calibri","sans-serif";'><span style='font-family:"Bookman Old Style","serif";'>f. &nbsp;The full Uniform Resource Locators (URL) clickstream to, through and from our website (including date and time); cookie number; products and/or content you viewed or searched for; page response times; download errors; length of visits to certain pages; page interaction information (such as scrolling, clicks, and mouse-overs).</span></p>
<p style='margin-top:6.0pt;margin-right:0in;margin-bottom:6.0pt;margin-left:21.3pt;font-size:11.0pt;font-family:"Calibri","sans-serif";'><span style='font-family:"Bookman Old Style","serif";'>g. &nbsp;By using this Website, you are agreeing that We may advertise your feedback on the Website and marketing materials.</span></p>
<p style='margin-top:6.0pt;margin-right:0in;margin-bottom:6.0pt;margin-left:21.3pt;font-size:11.0pt;font-family:"Calibri","sans-serif";'><span style='font-family:"Bookman Old Style","serif";'>h. &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp;We will retain your information as long as we require this to provide you with the services and for such period as mandated by the laws concerned.</span></p>
<p style='margin-top:6.0pt;margin-right:0in;margin-bottom:6.0pt;margin-left:21.3pt;font-size:11.0pt;font-family:"Calibri","sans-serif";'><span style='font-family:"Bookman Old Style","serif";'>i. &nbsp;If you opt to receive communication from us, subscribe to our mailing list or newsletters, enter into any of our competitions or provide us with your details at networking events, we may use your personal data for our legitimate interests in order to provide you with details about our goods, services, business updates and events.</span></p>
<p style='margin-top:6.0pt;margin-right:0in;margin-bottom:6.0pt;margin-left:21.3pt;font-size:11.0pt;font-family:"Calibri","sans-serif";'><span style='font-family:"Bookman Old Style","serif";'>j. &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;Please do not supply any other person&apos;s personal data to us, unless we prompt you to do so.</span></p>
<p style='margin-top:6.0pt;margin-right:0in;margin-bottom:6.0pt;margin-left:0in;font-size:11.0pt;font-family:"Calibri","sans-serif";'><strong><span style='font-family:"Bookman Old Style","serif";'>4. HOW WE USE INFORMATION</span></strong></p>
<p style='margin-top:6.0pt;margin-right:0in;margin-bottom:6.0pt;margin-left:21.3pt;font-size:11.0pt;font-family:"Calibri","sans-serif";'><span style='font-family:"Bookman Old Style","serif";'>a. &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp;We use the information we collect primarily to provide, maintain, protect, and improve our current products and services.</span></p>
<p style='margin-top:6.0pt;margin-right:0in;margin-bottom:6.0pt;margin-left:21.3pt;font-size:11.0pt;font-family:"Calibri","sans-serif";'><span style='font-family:"Bookman Old Style","serif";'>b. &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp;We use the information collected through this website as described in this policy and we may use your information to:</span></p>
<p style='margin-top:6.0pt;margin-right:0in;margin-bottom:6.0pt;margin-left:.5in;font-size:11.0pt;font-family:"Calibri","sans-serif";text-indent:-.55pt;'><span style='font-family:"Bookman Old Style","serif";'>I.&nbsp; &nbsp; &nbsp; &nbsp;&nbsp;Improve our services, Site and how we operate our businesses;</span></p>
<p style='margin-top:6.0pt;margin-right:0in;margin-bottom:6.0pt;margin-left:0in;font-size:11.0pt;font-family:"Calibri","sans-serif";text-indent:35.45pt;'><span style='font-family:"Bookman Old Style","serif";'>II. &nbsp; &nbsp; &nbsp;&nbsp;Create and maintain databases for providing donor information and blood bank services.</span></p>
<p style='margin-top:6.0pt;margin-right:0in;margin-bottom:6.0pt;margin-left:35.45pt;font-size:11.0pt;font-family:"Calibri","sans-serif";'><span style='font-family:"Bookman Old Style","serif";'>III. &nbsp; &nbsp; &nbsp;The enquiry data may be processed for the purposes of contact, collaboration, donor search, blood donation campaigns and/or relevant services and provide and deliver the products and services you request;</span></p>
<p style='margin-top:6.0pt;margin-right:0in;margin-bottom:6.0pt;margin-left:35.45pt;font-size:11.0pt;font-family:"Calibri","sans-serif";'><span style='font-family:"Bookman Old Style","serif";'>IV. &nbsp; &nbsp; &nbsp;Understand and enhance your experience using our Site, products, and services and make recommendations;</span></p>
<p style='margin-top:6.0pt;margin-right:0in;margin-bottom:6.0pt;margin-left:.5in;font-size:11.0pt;font-family:"Calibri","sans-serif";text-indent:-.55pt;'><span style='font-family:"Bookman Old Style","serif";'>V. &nbsp; &nbsp; &nbsp;&nbsp;Process, manage, complete, and account for transactions;</span></p>
<p style='margin-top:6.0pt;margin-right:0in;margin-bottom:6.0pt;margin-left:.5in;font-size:11.0pt;font-family:"Calibri","sans-serif";text-indent:-.55pt;'><span style='font-family:"Bookman Old Style","serif";'>VI. &nbsp; &nbsp; &nbsp;Provide customer support and respond to your requests,&nbsp;comments,&nbsp;and</span></p>
<p style='margin-top:6.0pt;margin-right:0in;margin-bottom:6.0pt;margin-left:.5in;font-size:11.0pt;font-family:"Calibri","sans-serif";text-indent:-.55pt;'><span style='font-family:"Bookman Old Style","serif";'>VII. &nbsp; &nbsp;&nbsp;Create and manage the online accounts you manage on our website;</span></p>
<p style='margin-top:6.0pt;margin-right:0in;margin-bottom:6.0pt;margin-left:35.45pt;font-size:11.0pt;font-family:"Calibri","sans-serif";'><span style='font-family:"Bookman Old Style","serif";'>VIII. &nbsp; &nbsp;Send you related information, including confirmations, invoices, technical notices, updates, security alerts and support and administrative messages;</span></p>
<p style='margin-top:6.0pt;margin-right:0in;margin-bottom:6.0pt;margin-left:35.45pt;font-size:11.0pt;font-family:"Calibri","sans-serif";'><span style='font-family:"Bookman Old Style","serif";'>IX. &nbsp; &nbsp; &nbsp;Communicate with you about promotions, upcoming events, and news about products and services;</span></p>
<p style='margin-top:6.0pt;margin-right:0in;margin-bottom:6.0pt;margin-left:35.45pt;font-size:11.0pt;font-family:"Calibri","sans-serif";'><span style='font-family:"Bookman Old Style","serif";'>X. &nbsp; &nbsp; &nbsp;&nbsp;We may process your personal information without your knowledge or consent where required by applicable law or regulation for the purposes of verification of identity or for prevention, detection, or investigation, including of cyber incidents, prosecution, and punishment of offences;</span></p>
<p style='margin-top:6.0pt;margin-right:0in;margin-bottom:6.0pt;margin-left:0in;font-size:11.0pt;font-family:"Calibri","sans-serif";text-indent:35.45pt;'><span style='font-family:"Bookman Old Style","serif";'>XI. &nbsp; &nbsp; &nbsp;Protect, investigate, and deter against fraudulent, unauthorized, or illegal activity.</span></p>
<p style='margin-top:6.0pt;margin-right:0in;margin-bottom:6.0pt;margin-left:21.3pt;font-size:11.0pt;font-family:"Calibri","sans-serif";'><span style='font-family:"Bookman Old Style","serif";'>c. &nbsp;&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;We may process information relating to transactions, including finding a blood donor and/or donating blood, that you enter on our platform and/or through our website or mobile application (&quot;transaction data&quot;). The transaction data may include name, mobile number, address, Hospital name, blood group required, required upto the date, your geographical location, device ID, IP address and the transaction details. The source of the transaction data is you and/or your partner. The transaction data may be processed for the tracking the geographical location of the blood donor and/or other services and keeping proper records of those transactions.</span></p>
<p style='margin-top:6.0pt;margin-right:0in;margin-bottom:6.0pt;margin-left:21.3pt;font-size:11.0pt;font-family:"Calibri","sans-serif";'><span style='font-family:"Bookman Old Style","serif";'>d. &nbsp;&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;We may process the searching data in hospital module for analytic purposes. We may use this data for research and to improve our services</span></p>
<p style='margin-top:6.0pt;margin-right:0in;margin-bottom:6.0pt;margin-left:21.3pt;font-size:11.0pt;font-family:"Calibri","sans-serif";'><span style='font-family:"Bookman Old Style","serif";'>e. &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp;We may process the information provide to us for the purpose of communicating through email notifications, mobile application notifications, messaging service notifications, blood requests near you and/or newsletters (&quot;notification data&quot;). The notification data may be processed for the purposes of sending you the relevant notifications, blood requests near you and/or newsletters. These notifications can be turned off partially by the user manually.</span></p>
<p style='margin-top:6.0pt;margin-right:0in;margin-bottom:6.0pt;margin-left:21.3pt;font-size:11.0pt;font-family:"Calibri","sans-serif";'><span style='font-family:"Bookman Old Style","serif";'>f. &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;We may process the blood request you post and/or content (story about the blood request) on our website or mobile application automatically or manually (&quot;publication data&quot;) to respective blood banks. We may share publication data via various communication channels for potential blood donors.</span></p>
<p style='margin-top:6.0pt;margin-right:0in;margin-bottom:6.0pt;margin-left:0in;font-size:11.0pt;font-family:"Calibri","sans-serif";'><strong><span style='font-family:"Bookman Old Style","serif";'>5. DATA TRANSFER</span></strong></p>
<p style='margin-top:6.0pt;margin-right:0in;margin-bottom:6.0pt;margin-left:21.3pt;font-size:11.0pt;font-family:"Calibri","sans-serif";'><span style='font-family:"Bookman Old Style","serif";'>a. &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp;Information about our users is an important part of our business and we take due care to protect the same. Your personal data held in our website and mobile application database will be stored on the servers of our hosting services providers identified at Namecheap.com.</span></p>
<p style='margin-top:6.0pt;margin-right:0in;margin-bottom:6.0pt;margin-left:21.3pt;font-size:11.0pt;font-family:"Calibri","sans-serif";'><span style='font-family:"Bookman Old Style","serif";'>b. &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp;We share your data with your consent to complete any transaction or provide any product or service you have requested or authorized. We also share data with our affiliates and subsidiaries, with hospitals, blood banksworking with us. &nbsp;We will share your contact details to the bloodbanks that accepts your blood request limited to your name, blood group, hospital name, required up to the date, geographical location, mobile number.</span></p>
<p style='margin-top:6.0pt;margin-right:0in;margin-bottom:6.0pt;margin-left:21.3pt;font-size:11.0pt;font-family:"Calibri","sans-serif";'><span style='font-family:"Bookman Old Style","serif";'>c. &nbsp;We may employ other companies and individuals to perform functions on our behalf.The functions include fulfilling orders for products or services, delivering packages, sending postal mail and e-mail, removing repetitive information from customer lists, providing marketing assistance, providing search results and links (including paid listings and links), processing payments, transmitting content, scoring credit risk, and providing customer service.</span></p>
<p style='margin-top:6.0pt;margin-right:0in;margin-bottom:6.0pt;margin-left:21.3pt;font-size:11.0pt;font-family:"Calibri","sans-serif";'><span style='font-family:"Bookman Old Style","serif";'>d. &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp;These third-party service providers have access to personal information needed to perform their functions but may not use it for other purposes. Further, they must process the personal information in accordance with this Privacy Policy and as permitted by applicable data protection laws.</span></p>
<p style='margin-top:6.0pt;margin-right:0in;margin-bottom:6.0pt;margin-left:21.3pt;font-size:11.0pt;font-family:"Calibri","sans-serif";'><span style='font-family:"Bookman Old Style","serif";'>e. &nbsp;We release accounts and other personal information when we believe it is appropriate to comply with the law, enforce or apply our conditions of use, and other agreements, and protect the rights, property or safety of Us, our users, or others. This includes exchanging information with other companies and organizations for fraud protection and credit risk reduction.</span></p>
<p style='margin-top:6.0pt;margin-right:0in;margin-bottom:6.0pt;margin-left:21.3pt;font-size:11.0pt;font-family:"Calibri","sans-serif";'><span style='font-family:"Bookman Old Style","serif";'>f. &nbsp;&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp;We may disclose your personal data where such disclosure is necessary for compliance with a legal obligation to which we are subject, or in order to protect your vital interests or the vital interests of another natural person. We may also disclose your personal data where such disclosure is necessary for purposes of obtaining or maintaining insurance coverage, managing risks, obtaining professional advice, or the establishment, exercise or defence of legal claims, whether in court proceedings or in an administrative or out-of-court procedure.</span></p>
<p style='margin-top:6.0pt;margin-right:0in;margin-bottom:6.0pt;margin-left:0in;font-size:11.0pt;font-family:"Calibri","sans-serif";'><strong><span style='font-family:"Bookman Old Style","serif";'>6. COOKIES</span></strong></p>
<p style='margin-top:6.0pt;margin-right:0in;margin-bottom:6.0pt;margin-left:21.3pt;font-size:11.0pt;font-family:"Calibri","sans-serif";'><span style='font-family:"Bookman Old Style","serif";'>a. &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp;We use cookies on our website and mobile application. Insofar as those cookies are not strictly necessary for the provision of bloodlinks.in and services, by using our website or mobile application you permit us to use of cookies when you visit our website or mobile application.</span></p>
<p style='margin-top:6.0pt;margin-right:0in;margin-bottom:6.0pt;margin-left:21.3pt;font-size:11.0pt;font-family:"Calibri","sans-serif";'><span style='font-family:"Bookman Old Style","serif";'>b. &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp;These are small text files stored on your computer&apos;s main memory. These cookies are deleted after you close the browser. Other cookies remain on your computer (long-term cookies) and permit its recognition on your next visit. This allows us to improve your access to our site. This helps us to learn more about your interests and provides you with essential features and services, including:</span></p>
<p style='margin-top:6.0pt;margin-right:0in;margin-bottom:6.0pt;margin-left:.5in;font-size:11.0pt;font-family:"Calibri","sans-serif";text-indent:-.55pt;'><span style='font-family:"Bookman Old Style","serif";'>I. &nbsp; &nbsp; &nbsp; &nbsp;Keeping track of your requests and requirements.</span></p>
<p style='margin-top:6.0pt;margin-right:0in;margin-bottom:6.0pt;margin-left:0in;font-size:11.0pt;font-family:"Calibri","sans-serif";text-indent:35.45pt;'><span style='font-family:"Bookman Old Style","serif";'>II. &nbsp; &nbsp; &nbsp;&nbsp;Conducting research and diagnostics to improve the content, products, and services.</span></p>
<p style='margin-top:6.0pt;margin-right:0in;margin-bottom:6.0pt;margin-left:.5in;font-size:11.0pt;font-family:"Calibri","sans-serif";text-indent:-.55pt;'><span style='font-family:"Bookman Old Style","serif";'>III. &nbsp; &nbsp; &nbsp;Preventing fraudulent activity.</span></p>
<p style='margin-top:6.0pt;margin-right:0in;margin-bottom:6.0pt;margin-left:.5in;font-size:11.0pt;font-family:"Calibri","sans-serif";text-indent:-.55pt;'><span style='font-family:"Bookman Old Style","serif";'>IV. &nbsp; &nbsp; &nbsp;Improving security.</span></p>
<p style='margin-top:6.0pt;margin-right:0in;margin-bottom:6.0pt;margin-left:21.3pt;font-size:11.0pt;font-family:"Calibri","sans-serif";'><span style='font-family:"Bookman Old Style","serif";'>c. &nbsp;Our cookies allow you to take advantage of some of our essential features. For instance, if you block or otherwise reject our cookies, you will not be able to use any products or services that require you to sign in.</span></p>
<p style='margin-top:6.0pt;margin-right:0in;margin-bottom:6.0pt;margin-left:35.8pt;font-size:11.0pt;font-family:"Calibri","sans-serif";text-indent:-14.5pt;'><span style='font-family:"Bookman Old Style","serif";'>d. &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp;Our service providers use cookies and those cookies may be stored on your computer or mobile devices when you visit our website or mobile application. We use Google Analytics. Google Analytics gathers information about the use of our website by means of cookies. The information gathered is used to create reports about the use of our website. You can find out more about Google&apos;s use of information byvisiting&nbsp;</span><a href="https://www.google.com/policies/privacy/partners/" target="_blank"><span style='font-family:"Bookman Old Style","serif";color:windowtext;text-decoration:none;'>https://www.google.com/policies/privacy/partners/</span></a><span style='font-family:"Bookman Old Style","serif";'>&nbsp;and you can review Google&apos;s privacy policy at&nbsp;</span><a href="https://policies.google.com/privacy" target="_blank"><span style='font-family:"Bookman Old Style","serif";color:windowtext;text-decoration:none;'>https://policies.google.com/privacy</span></a><span style='font-family:"Bookman Old Style","serif";'>.</span></p>
<p style='margin-top:6.0pt;margin-right:0in;margin-bottom:6.0pt;margin-left:21.3pt;font-size:11.0pt;font-family:"Calibri","sans-serif";'><span style='font-family:"Bookman Old Style","serif";'>e. &nbsp;Approved third parties also may set cookies when you interact with Our services.</span></p>
<p style='margin-top:6.0pt;margin-right:0in;margin-bottom:6.0pt;margin-left:21.3pt;font-size:11.0pt;font-family:"Calibri","sans-serif";'><span style='font-family:"Bookman Old Style","serif";'>f. &nbsp;Third parties include search engines, providers of measurement and analytics services, social media networks, and advertising companies.</span></p>
<p style='margin-top:6.0pt;margin-right:0in;margin-bottom:6.0pt;margin-left:21.3pt;font-size:11.0pt;font-family:"Calibri","sans-serif";'><span style='font-family:"Bookman Old Style","serif";'>g. &nbsp;Third parties use cookies in the process of delivering content, including ads relevant to your interests, to measure the effectiveness of their ads, and to perform services on behalf of Us.</span></p>
<p style='margin-top:6.0pt;margin-right:0in;margin-bottom:6.0pt;margin-left:21.3pt;font-size:11.0pt;font-family:"Calibri","sans-serif";'><span style='font-family:"Bookman Old Style","serif";'>h. &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp;You can prevent the storage of cookies by choosing a &quot;disable cookies&quot; option in your browser settings. But this can limit the functionality of&nbsp;our&nbsp;services. Most browsers allow you to refuse to accept cookies and to delete cookies. The methods for doing so vary from browser to browser, and from version to version. You can however obtain up-to-date information about blocking and deleting cookies via these links:</span></p>
<p style='margin-top:6.0pt;margin-right:0in;margin-bottom:6.0pt;margin-left:35.45pt;font-size:11.0pt;font-family:"Calibri","sans-serif";line-height:normal;vertical-align:baseline;'><a href="https://support.google.com/chrome/answer/95647"><span style='font-family:"Bookman Old Style","serif";border:none windowtext 1.0pt;padding:0in;'>https://support.google.com/chrome/answer/95647</span></a><span style='font-family:"Bookman Old Style","serif";color:#5E5E5E;'>&nbsp;(Chrome);</span></p>
<p style='margin-top:6.0pt;margin-right:0in;margin-bottom:6.0pt;margin-left:35.45pt;font-size:11.0pt;font-family:"Calibri","sans-serif";line-height:normal;vertical-align:baseline;'><a href="https://support.mozilla.org/en-US/kb/enable-and-disable-cookies-website-preferences"><span style='font-family:"Bookman Old Style","serif";border:none windowtext 1.0pt;padding:0in;'>https://support.mozilla.org/en-US/kb/enable-and-disable-cookies-website-preferences</span></a><span style='font-family:"Bookman Old Style","serif";color:#5E5E5E;'>&nbsp;(Firefox);</span></p>
<p style='margin-top:6.0pt;margin-right:0in;margin-bottom:6.0pt;margin-left:35.45pt;font-size:11.0pt;font-family:"Calibri","sans-serif";line-height:normal;vertical-align:baseline;'><a href="https://help.opera.com/en/latest/security-and-privacy/"><span style='font-family:"Bookman Old Style","serif";border:none windowtext 1.0pt;padding:0in;'>https://help.opera.com/en/latest/security-and-privacy/</span></a><span style='font-family:"Bookman Old Style","serif";color:#5E5E5E;'>&nbsp;(Opera);</span></p>
<p style='margin-top:6.0pt;margin-right:0in;margin-bottom:6.0pt;margin-left:35.45pt;font-size:11.0pt;font-family:"Calibri","sans-serif";line-height:normal;vertical-align:baseline;'><a href="https://support.microsoft.com/en-gb/help/17442/windows-internet-explorer-delete-manage-cookies"><span style='font-family:"Bookman Old Style","serif";border:none windowtext 1.0pt;padding:0in;'>https://support.microsoft.com/en-gb/help/17442/windows-internet-explorer-delete-manage-cookies</span></a><span style='font-family:"Bookman Old Style","serif";color:#5E5E5E;'>&nbsp;(Internet Explorer);</span></p>
<p style='margin-top:6.0pt;margin-right:0in;margin-bottom:6.0pt;margin-left:35.45pt;font-size:11.0pt;font-family:"Calibri","sans-serif";line-height:normal;vertical-align:baseline;'><a href="https://support.apple.com/en-gb/guide/safari/manage-cookies-and-website-data-sfri11471/mac"><span style='font-family:"Bookman Old Style","serif";border:none windowtext 1.0pt;padding:0in;'>https://support.apple.com/en-gb/guide/safari/manage-cookies-and-website-data-sfri11471/mac</span></a><span style='font-family:"Bookman Old Style","serif";color:#5E5E5E;'>&nbsp;(Safari); and</span></p>
<p style='margin-top:6.0pt;margin-right:0in;margin-bottom:6.0pt;margin-left:35.45pt;font-size:11.0pt;font-family:"Calibri","sans-serif";line-height:normal;vertical-align:baseline;'><a href="https://privacy.microsoft.com/en-us/windows-10-microsoft-edge-and-privacy"><span style='font-family:"Bookman Old Style","serif";border:none windowtext 1.0pt;padding:0in;'>https://privacy.microsoft.com/en-us/windows-10-microsoft-edge-and-privacy</span></a><span style='font-family:"Bookman Old Style","serif";color:#5E5E5E;'>&nbsp;(Edge).</span></p>
<p style='margin-top:6.0pt;margin-right:0in;margin-bottom:6.0pt;margin-left:.5in;font-size:11.0pt;font-family:"Calibri","sans-serif";'><span style='font-family:"Bookman Old Style","serif";'>&nbsp;</span></p>
<p style='margin-top:6.0pt;margin-right:0in;margin-bottom:6.0pt;margin-left:0in;font-size:11.0pt;font-family:"Calibri","sans-serif";'><strong><span style='font-family:"Bookman Old Style","serif";'>6. DATA SECURITY</span></strong></p>
<p style='margin-top:6.0pt;margin-right:0in;margin-bottom:6.0pt;margin-left:21.3pt;font-size:11.0pt;font-family:"Calibri","sans-serif";'><span style='font-family:"Bookman Old Style","serif";'>a. &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp;We take due care to protect customer data. Technical measures are in place to prevent unauthorized or unlawful access to data and against accidental loss or destruction of, or damage to, data. The employees who are dealing with the data have been trained to protect the data from any illegal or unauthorized usage.</span></p>
<p style='margin-top:6.0pt;margin-right:0in;margin-bottom:6.0pt;margin-left:21.3pt;font-size:11.0pt;font-family:"Calibri","sans-serif";'><span style='font-family:"Bookman Old Style","serif";'>b. &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp;We work to protect the security of your information during transmission by using Secure Sockets Locker (SSL) software, which encrypts the information you input. SSL allows sensitive information such as UID&apos;s and login credentials to be transmitted securely.</span></p>
<p style='margin-top:6.0pt;margin-right:0in;margin-bottom:6.0pt;margin-left:21.3pt;font-size:11.0pt;font-family:"Calibri","sans-serif";'><span style='font-family:"Bookman Old Style","serif";'>c. &nbsp;We maintain physical, electronic, and procedural safeguards in connection with the collection, storage, and disclosure of personal customer information.</span></p>
<p style='margin-top:6.0pt;margin-right:0in;margin-bottom:6.0pt;margin-left:21.3pt;font-size:11.0pt;font-family:"Calibri","sans-serif";'><span style='font-family:"Bookman Old Style","serif";'>d. &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp;We take reasonable steps to help protect your personal information in an effort to prevent loss, misuse, unauthorized access, disclosure alteration and destruction. It is your responsibility to protect your user names and passwords to help prevent anyone from accessing or abusing your accounts and services. You should not use or reuse the same passwords you use with other accounts as your password for our services.</span></p>
<p style='margin-top:6.0pt;margin-right:0in;margin-bottom:6.0pt;margin-left:21.3pt;font-size:11.0pt;font-family:"Calibri","sans-serif";'><span style='font-family:"Bookman Old Style","serif";'>e. &nbsp;It is important for you to protect against unauthorized access to your password and your computers, devices, and applications. Be sure to sign off when you finish using a shared computer.</span></p>
<p style='margin-top:6.0pt;margin-right:0in;margin-bottom:6.0pt;margin-left:21.3pt;font-size:11.0pt;font-family:"Calibri","sans-serif";'><span style='font-family:"Bookman Old Style","serif";'>f. &nbsp;The information you provide to us is shared on our secure servers. We have implemented appropriate physical, technical and organizational measures designed to secure your information against accidental loss and unauthorized access, use, alteration, or disclosure. In addition, we limit access to personal data to those employees, agents, contractors, and other third parties that have a legitimate business need for such access.</span></p>
<p style='margin-top:6.0pt;margin-right:0in;margin-bottom:6.0pt;margin-left:21.3pt;font-size:11.0pt;font-family:"Calibri","sans-serif";'><span style='font-family:"Bookman Old Style","serif";'>g. &nbsp;Information collected from you will be stored for such period as required to complete the transaction entered into with you or such period as mandated under the applicable laws.</span></p>
<p style='margin-top:6.0pt;margin-right:0in;margin-bottom:6.0pt;margin-left:21.3pt;font-size:11.0pt;font-family:"Calibri","sans-serif";'><span style='font-family:"Bookman Old Style","serif";'>h. &nbsp;&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;The hosting facilities for our website are situated in United States and appropriate safeguards will protect data in the host country, the personal data that you submit for publication through our website or mobile application may be available, via the internet, around the world. We cannot completely prevent the use (or misuse) of such personal data by others.</span></p>
<p style='margin-top:6.0pt;margin-right:0in;margin-bottom:6.0pt;margin-left:0in;font-size:11.0pt;font-family:"Calibri","sans-serif";'><strong><span style='font-family:"Bookman Old Style","serif";'>7. LINKS TO THIRD-PARTY SITES/APPS</span></strong></p>
<p style='margin-top:6.0pt;margin-right:0in;margin-bottom:6.0pt;margin-left:21.3pt;font-size:11.0pt;font-family:"Calibri","sans-serif";'><span style='font-family:"Bookman Old Style","serif";'>Our Site may, from time to time, contain links to and from other websites of third parties.Please note that if you follow a link to any of these websites, such websites will apply different terms to the collection and privacy of your personal data, and we do not accept any responsibility or liability for these policies. When you leave our Site, we encourage you to read the privacy policy of every website you visit.</span></p>
<p style='margin-top:6.0pt;margin-right:0in;margin-bottom:6.0pt;margin-left:0in;font-size:11.0pt;font-family:"Calibri","sans-serif";'><strong><span style='font-family:"Bookman Old Style","serif";'>8. SOCIAL NETWORK PLUGINS</span></strong></p>
<p style='margin-top:6.0pt;margin-right:0in;margin-bottom:6.0pt;margin-left:21.3pt;font-size:11.0pt;font-family:"Calibri","sans-serif";'><span style='font-family:"Bookman Old Style","serif";'>This Website incorporates plugins and/or buttons for social networks, in order to allow easy sharing on your favourite social networks. These plugins are programmed so as not to set any cookies when assessing the page to safeguard the privacy of users. Cookies may be set if you make voluntary use of the plugin. The collection and use of information obtained by means of the plugin are governed by the respective privacy policies of the social&nbsp;networks.</span></p>
<p style='margin-top:6.0pt;margin-right:0in;margin-bottom:6.0pt;margin-left:0in;font-size:11.0pt;font-family:"Calibri","sans-serif";'><strong><span style='font-family:"Bookman Old Style","serif";'>9. SHARING OF PERSONAL INFORMATION</span></strong></p>
<p style='margin-top:6.0pt;margin-right:0in;margin-bottom:6.0pt;margin-left:21.3pt;font-size:11.0pt;font-family:"Calibri","sans-serif";'><span style='font-family:"Bookman Old Style","serif";'>a. &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp;We do not share your personal data with third parties without your prior consent other than:</span></p>
<p style='margin-top:6.0pt;margin-right:0in;margin-bottom:6.0pt;margin-left:35.45pt;font-size:11.0pt;font-family:"Calibri","sans-serif";'><span style='font-family:"Bookman Old Style","serif";'>I.&nbsp; &nbsp; &nbsp; &nbsp;&nbsp;With third parties who work on our behalf provided such third parties adhere to the data protection principles set out in the IT Act, 2000 (21 of 2000) and other applicable legislation, or enter into a written agreement with Us requiring that the third party provide at least the same level of privacy protection as is required by such principles;</span></p>
<p style='margin-top:6.0pt;margin-right:0in;margin-bottom:6.0pt;margin-left:0in;font-size:11.0pt;font-family:"Calibri","sans-serif";text-indent:35.45pt;'><span style='font-family:"Bookman Old Style","serif";'>II. &nbsp; &nbsp; &nbsp;&nbsp;To comply with laws or to respond to lawful requests and legal process;</span></p>
<p style='margin-top:6.0pt;margin-right:0in;margin-bottom:6.0pt;margin-left:35.45pt;font-size:11.0pt;font-family:"Calibri","sans-serif";'><span style='font-family:"Bookman Old Style","serif";'>III. &nbsp; &nbsp; &nbsp;To protect the rights and property of Us, our agents, customers, and others including to enforce our agreements, policies, and terms of use;</span></p>
<p style='margin-top:6.0pt;margin-right:0in;margin-bottom:6.0pt;margin-left:0in;font-size:11.0pt;font-family:"Calibri","sans-serif";text-indent:35.45pt;'><span style='font-family:"Bookman Old Style","serif";'>IV. &nbsp; &nbsp; &nbsp;In an emergency, including to protect the personal safety of any person; and</span></p>
<p style='margin-top:6.0pt;margin-right:0in;margin-bottom:6.0pt;margin-left:35.45pt;font-size:11.0pt;font-family:"Calibri","sans-serif";'><span style='font-family:"Bookman Old Style","serif";'>V. &nbsp; &nbsp; &nbsp;&nbsp;For the purpose of a business deal (or negotiation of a business deal) involving the sale or transfer of all or a part of our business or assets (business deals may include, for example, any merger, financing, acquisition, divestiture, or bankruptcy transaction or proceeding).</span></p>
<p style='margin-top:6.0pt;margin-right:0in;margin-bottom:6.0pt;margin-left:0in;font-size:11.0pt;font-family:"Calibri","sans-serif";'><strong><span style='font-family:"Bookman Old Style","serif";'>10. CHILDREN</span></strong></p>
<p style='margin-top:6.0pt;margin-right:0in;margin-bottom:6.0pt;margin-left:21.3pt;font-size:11.0pt;font-family:"Calibri","sans-serif";'><span style='font-family:"Bookman Old Style","serif";'>If you are under 18, or the age of majority in the jurisdiction in which you reside, you may only use Our Website with the consent of your parent or legal guardian. In any case, We will not be liable for any cause of action that arose due to non-compliance with this section.</span></p>
<p style='margin-top:6.0pt;margin-right:0in;margin-bottom:6.0pt;margin-left:0in;font-size:11.0pt;font-family:"Calibri","sans-serif";'><strong><span style='font-family:"Bookman Old Style","serif";color:red;'>11.&nbsp;</span></strong></p>
<p style='margin-top:6.0pt;margin-right:0in;margin-bottom:6.0pt;margin-left:0in;font-size:11.0pt;font-family:"Calibri","sans-serif";'><strong><span style='font-family:"Bookman Old Style","serif";'>12. CHANGES TO THIS POLICY</span></strong></p>
<p style='margin-top:6.0pt;margin-right:0in;margin-bottom:6.0pt;margin-left:21.3pt;font-size:11.0pt;font-family:"Calibri","sans-serif";'><span style='font-family:"Bookman Old Style","serif";'>We may change this policy from time to time. If we make any changes to this policy, we will change the &quot;Last Updated&quot; date above. You agree that your continued use of our services after such changes have been published to our services will constitute your acceptance of such revised policy.</span></p>
<p style='margin-top:6.0pt;margin-right:0in;margin-bottom:6.0pt;margin-left:0in;font-size:11.0pt;font-family:"Calibri","sans-serif";'><strong><span style='font-family:"Bookman Old Style","serif";'>13. NEWSLETTER</span></strong></p>
<p style='margin-top:6.0pt;margin-right:0in;margin-bottom:6.0pt;margin-left:21.3pt;font-size:11.0pt;font-family:"Calibri","sans-serif";'><span style='font-family:"Bookman Old Style","serif";'>a. &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp;Following your subscription to the newsletter, your e-mail address is used for our advertising purposes until you cancel the newsletter again. Cancellation is possible at any time. The following consent has been expressly granted by you separately, or possibly in the course of an ordering process: I am accepting to receive newsletters from this website), you may revoke your consent at any time with future effect. If you no longer want to receive the newsletter, then unsubscribe by clicking on the unsubscribe option given in the email footer.</span></p>
<p style='margin-top:6.0pt;margin-right:0in;margin-bottom:6.0pt;margin-left:21.3pt;font-size:11.0pt;font-family:"Calibri","sans-serif";'><span style='font-family:"Bookman Old Style","serif";'>If you have any concerns about privacy or grievances with Us, please contact us with a thorough description and we will try to resolve the issue for you.</span></p>
<p style='margin-top:6.0pt;margin-right:0in;margin-bottom:6.0pt;margin-left:0in;font-size:11.0pt;font-family:"Calibri","sans-serif";'><strong><span style='font-family:"Bookman Old Style","serif";'>14. CONTACT&nbsp;DETAILS</span></strong></p>
<p style='margin-top:6.0pt;margin-right:0in;margin-bottom:6.0pt;margin-left:21.3pt;font-size:11.0pt;font-family:"Calibri","sans-serif";'><span style='font-family:"Bookman Old Style","serif";'>This website is owned and operated by&nbsp;Vita Hee Care Trust. We are registered in India under registration number&nbsp;XXXXXXXXXX, and our registered office is at&nbsp;B-37, ASHOK VIHAR, GIRDHAR MARG, MALVIYA NAGAR, JAIPUR, RAJASTHAN (INDIA)</span></p>
<p style='margin-top:6.0pt;margin-right:0in;margin-bottom:6.0pt;margin-left:21.3pt;font-size:11.0pt;font-family:"Calibri","sans-serif";'><span style='font-family:"Bookman Old Style","serif";'>You can contact us by post, to the postal address given above; using our website or mobile application contact form; by telephone, on the contact number published on our website or mobile application; or by email, using the email address published on our website or mobile application.</span></p>
<p style='margin-top:6.0pt;margin-right:0in;margin-bottom:6.0pt;margin-left:21.3pt;font-size:11.0pt;font-family:"Calibri","sans-serif";'><strong><span style='font-family:"Bookman Old Style","serif";color:#5E5E5E;'>Data protection officer:&nbsp;</span></strong><span style='font-family:"Bookman Old Style","serif";color:#5E5E5E;'>O</span><span style='font-family:"Bookman Old Style","serif";'>ur data protection officer&apos;s contact details are:&nbsp;</span></p>
<p style='margin-top:6.0pt;margin-right:0in;margin-bottom:6.0pt;margin-left:0in;font-size:11.0pt;font-family:"Calibri","sans-serif";text-indent:.5in;line-height:normal;vertical-align:baseline;'><a href="mailto:info@bloodlinks.in"><span style='font-family:"Bookman Old Style","serif";'>info@bloodlinks.in</span></a></p>
</div>